#!/bin/sh

echo "=========================="
echo "Running Pre-commit...🚀🚀🚀"
echo "=========================="

npx lint-staged
RESULT=$?

if [ $RESULT -ne 0 ]; then
  echo "❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌"
  echo "Pre-commit checks failed!"
  echo "❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌"
  exit 1
fi

echo "✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅"
echo "All pre-commit checks passed successfully."
echo "✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅"

exit 0
